apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gbh8w55uh-java-springboot 
  janus-idp.io/tekton: gbh8w55uh-java-springboot
  backstage.io/kubernetes-id: gbh8w55uh-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gbh8w55uh-java-springboot
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml